services:
  api:
    container_name: urlshortner-api
    build:
      context: .
      dockerfile: src/UrlShortner.RestApi/Dockerfile.dev
    volumes:
      - .:/app
      # Exclude build output folders to avoid conflicts/permissions issues
      - /app/obj/ 
      - /app/bin/
    ports:
      - "5000:8080"
    command: 
        - dotnet
        # - watch
        - run
        # FIX: Changed the relative path to an absolute path for reliability
        - --project
        - /app/src/UrlShortner.RestApi/UrlShortner.RestApi.csproj 
        - --urls
        - http://0.0.0.0:8080
        # - --no-restore # Skip restore since we did it in the Dockerfile.dev
    depends_on:
        - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__TinyUrlDb=Server=urlshortner-mssql,1433;Database=Tinyurl;User Id=sa;Password=Admin@123;TrustServerCertificate=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: urlshortner-mssql
    environment:
      SA_PASSWORD: "Admin@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  redis:
    image: redis:7
    container_name: redis
    ports:
        - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
        - redis_data:/data
volumes:
  sql_data:
  redis_data:

networks:
  appnetwork:
    driver: bridge
